### ISSUE TITLE
Multilang support?

### ISSUE THREAD

**Issue by ViBE-HU** [Blackstareye/toggleAudio-blackeyeprojects.de#14]
Opened an issue as you requested.

So please add multilang support. You don't have to do the translation jobs. The community will do that part as usual.

**Comment by Blackstareye** [comment]
Hey unfortunately this is not how it works. 
I already had the infrastructure for multilang support. But in my first review, it was dropped cause I had only English.

So I need the required languages and the keywords you need.

Otherwise it will be "just english" :/

**Comment by Blackstareye** [comment]
https://github.com/Blackstareye/toggleAudio-blackeyeprojects.de/blob/cc777dbe808f36621ec6f27e8ee5bd920bc37157/po/toggleAudio%40blackeyeprojects.de.pot

this was the commit that i had to rollback.
so it was already there :)

**Comment by Blackstareye** [comment]
@ViBE-HU 
I added this PR so far.

#15 

is there something missing?

**Comment by ViBE-HU** [comment]
Sadly I have zero clue about how to implement gettext or anything else. I mean I'm not a programmer :/

But if you need a string to start then create the hu.po (hungarian) and you can translate `Switch headphone` as `Fejhallgató`.

**Comment by Blackstareye** [comment]
Issue will be done with #15 . It is in review right now :) 
I added the german translation and it worked :)
Should also do for other files then :) 

<hr>
I would appreciate it if you let a review here [review on https://extensions.gnome.org/extension/7080/toggle-headphone/](https://extensions.gnome.org/extension/7080/toggle-headphone/)    :>

This helps the extension to grow so others can see and use this extension as well :)
This also helps to get maybe someday a donation which supports projects like that and helps me doing freelancing stuff :)

**Comment by ViBE-HU** [comment]
Will do. Btw is it normal that the commit is still not merged?

**Comment by Blackstareye** [comment]
yes, I wait until the review is done :) Now it is done :)

**Comment by Blackstareye** [comment]
just fyi @ViBE-HU: 
 @goat865  added hungarian translation  :)

**Comment by ViBE-HU** [comment]
cool. i already did the job but whatever.

**Comment by Blackstareye** [comment]
That's unfortunate ^^' 
but yeah, this can happen :x

**Comment by Blackstareye** [comment]
I consider this as done :)

**Comment by ViBE-HU** [comment]
absolutely. but it is a pretty @ss move to after all tbh to approve his translation.

**Comment by Blackstareye** [comment]
Not really.

This issue was about adding the multi lang support.
This was your request, and this was done.

If you said to me that you are going to do a translation, I could had take actions there.

But:
 * there were no issue
 * no pr
 * no comment 
that **you** are going to do a translation. :/ 

I just was not aware (and I am sorry for that), that you are also wanted to contribute. :/

**Comment by ViBE-HU** [comment]
i'm not gonna argue but i requested it because i already planning to ad a translation asap for better integrity. i check extensions and then request if i find the idea useful and the developer still not implemented gettext. it would be lame to just request a key feature to let others do the subsequent job. like a stalker or what. i thought it was clear.

**Comment by Blackstareye** [comment]
Then I am sorry, it wasnt clear for me.

I also checked now  if you had a  public fork. Not the case, 
so I just thought you wanted that feature, so that maybe in future you can contribute or that this gives others the ability. But not that you are doing the translation right now.
Actually, I thought you are happy that already somebody had the same idea and that this would you save time and energy. 
Turns out I was wrong there.

So yeah, it is what it is now.
But for me, it was anything, but not clear to me that you are in the progress of a translation-contribution here. :/

I am happy about any contribution, but please give me some notification beforehead about it, so I can plan this a bit better IF there are circumstances, in which two contributers work on the same topic / issue ^^'

Just any information is better than no information about progress ^^'

**Comment by ViBE-HU** [comment]
there is no written rule how to contribute translations here. the decision is up on the developer to care about multilang implementation. but usually users like me request first the implementation then do their part. and when the extension gets enough attention other users will join and do their part (and hopefully keep maintaining it). and if the developer find it okay then approve these kind of commits. this is how the community works. and i am part of the community too. this why i said that _"community will do that part as usual"_. but the first step is always the dev's. i have lack of knowledge but i'm good at translation. that's why i requested. that's my routine and role here in general.

the commit not done yet because i don't wanted to push half baked stuff. and now it became somehow needless.

**Comment by Blackstareye** [comment]
Closed the convo here 
cause we go round in circles here.

I understand your point but I also stand with my point.
Make it please more clear, and give information beforehead to avoid such situation :)
