### ISSUE TITLE
Monochrome icon

### ISSUE THREAD

**Issue by goat865** [Blackstareye/toggleAudio-blackeyeprojects.de#8]
As the other buttons have monochrome icons, I think it would be great if the extension had at least an option to switch between colored and monochrome icons.

**Comment by Blackstareye** [comment]
Hey :), 

I am using  these icons 
https://github.com/Blackstareye/toggleAudio-blackeyeprojects.de/blob/217878386a44d2332d4ad3ed24ed36cc50c7fcdb/extension.js#L95-L100

which is this one
![grafik](https://github.com/user-attachments/assets/0ab17cac-e069-46de-b67e-dadf7e70b48e)


and that one
![grafik](https://github.com/user-attachments/assets/42ae6e53-1a17-409e-a81a-1af68b9bd914)


so it **is** monochrome.

If you have another icon suggest for these.

Just mention it here and I can test it's look :D    

Ps:
But I saw, that they are different "shown" depending on the OS.
On Ubuntu they are sometimes colorful depending on the theme.

**Comment by goat865** [comment]
Well look at that, you're right. I'm using Kora as my icon theme and apparently it changes the icon of your extension as well.

![image](https://github.com/user-attachments/assets/53319716-feea-4e6d-9b74-0f710f8bb5b1)

I wonder why not to a monochrome icon like the others tho.

**Comment by Blackstareye** [comment]
strange 😄 maybe,  you can file an issue to the theme so they are aware of that ? afaik there is also a flatpak called icons which shows all available icons. Maybe you can see there if your package contains other not monochrome icons as well and if it is a design choice :D 

in case you want all icons be  monochrome :)

**Comment by Blackstareye** [comment]
@goat865  i saw that there are also `symbolic` icons.
So i changed it and made another panel for styling.

I also got a bit of time this weekend, so I also made it **possible** (its not bugfree because of wrong input --> wrong output) to change the icons as well. They are now a gsetting:
* one for monochrome / symbolic
* one for colorful

![grafik](https://github.com/user-attachments/assets/e1b8a14a-b576-46f0-8214-b93c8d4b5e80)

PR is this one #9 

it will be available soon. I will pack it, test it and then it's available as soon as it is approved by gnome :)

**Comment by Blackstareye** [comment]
@goat865  good news it's approved :D

**Comment by goat865** [comment]
Great, that was fast. Thank you :)

**Comment by Blackstareye** [comment]
@goat865  hope it's now more controllable for you which icon is shown :D

**Comment by goat865** [comment]
Yeah, I hope so. I'll let you know once I get home.

**Comment by goat865** [comment]
Everything looks good, thanks again :D
